### ISSUE TITLE
DateTime of a field

### ISSUE THREAD

**Issue by andreaPorini** [DigitalFlow/Xrm-Templating-Language#14]
Hi @DigitalFlow 

i found a problem in the language, if i extract a datetime field the time is converted to UTC.

In CRM the timezone selected is GMT+1 and the appointment of 6/03/2019 18.30 is converted to 6/03/2019 5.30.

How can i fix this issue?

Thank you,
Andrea

**Comment by DigitalFlow** [comment]
Hi @andreaPorini 

CRM returns the UTC values by default. I will think of some new methods for converting from and to UTC regarding timezones.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
For the time being, you could use a fetch for retrieving the date field, as fetch will return the user local time value by default. But that might be a bit much for a workaround.

**Comment by andreaPorini** [comment]
Hi @DigitalFlow ,

using the FetchXml i will get the real data? If this is the behavior I think it's a good workaround.

I'll try it, thank you very much for the suggestion!

Best regards,
Andrea

**Comment by andreaPorini** [comment]
Unfortunatly, also the fetch extract the value in UTC format.

I will look for your implementation!

Regards,
Andrea

**Comment by DigitalFlow** [comment]
@andreaPorini 
Found that out right now as well, must be specific to fetches in XML reports then...
I'll add some date functions and notify you.

**Comment by DigitalFlow** [comment]
Hi @andreaPorini,

Just so that you know that some design progress has been made:
- There will be methods for getting Local Time of a UTC DateTime for a given User ID and vice versa
- There will be methods for getting a Local Timein a user fixed time zone by UTC DateTime by target time zone id

I hope to get it done soon.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hey @andreaPorini,

This feature has been implemented in v3.4.0.
Please install the latest solution and check the [ConvertDateTime Function](https://github.com/DigitalFlow/Xrm-Templating-Language#convertdatetime).

Kind Regards,
Florian

**Comment by andreaPorini** [comment]
Hi @DigitalFlow,

thank you very much, i will update and try the new functions as soon as possible!

Best regards,
Andrea

**Comment by DigitalFlow** [comment]
Great, 

I'll close this issue, please ping back if you experience any issues.

Kind Regards,
Florian
