### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by luca0071** [DigitalFlow/Xrm-Templating-Language#2]
Hi. tool's awesome. 
it might be useful to be able to:
- define a custom table layout (you have just one layout possible).
- being able to retrieve template from an attribute of a lookup field

**Comment by DigitalFlow** [comment]
Hi @luca0071,

thanks for your feedback.
I will add your feature requests to my todo list.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hey @luca0071,

thanks again for your input.
Your feature requests have been implemented in Release v3.0.1.

Kind Regards,
Florian

**Comment by luca0071** [comment]
Hi Florian, thank you very much for your implementation. we'll go thru it and give feedback to you soon, and maybe some new nice features request.
grazie
